import json
import logging

import httpx
from openai import APIError, APITimeoutError, RateLimitError

from sergeant.config import Settings
from sergeant.models.azure_provider import AzureOpenAIProvider
from sergeant.models.base import ModelMessage, ModelResponse
from sergeant.models.ollama_provider import OllamaProvider
from sergeant.skills.registry import skill_registry
from sergeant.skills.pending import PendingConfirmation, pending_store
from sergeant.memory import SQLiteMemory

logger = logging.getLogger(__name__)

MAX_TOOL_ITERATIONS = 5

SYSTEM_PROMPT = (
    "You are Sergeant, a local AI agent running on a Raspberry Pi. "
    "Respond in English, clearly, helpfully, and directly. "
    "If you need to assume something, state it explicitly. "
    "You have tools (skills) available to check the actual system status "
    "or execute actions. Use them when the prompt requires it instead of inventing data. "
    "IMPORTANT: when the user requests an action that corresponds to an available "
    "tool, CALL that tool directly. Do not explain in text that you 'need confirmation' "
    "nor ask 'do you confirm?' in natural language -- the confirmation system is "
    "automatically handled outside of your response when the tool requires it. "
    "Your job is to invoke the function; the user will see the confirmation prompt "
    "generated by the system, not by you."
)

class ConfirmationRequired(Exception):
    def __init__(self, tool_name: str, tool_args: dict):
        self.tool_name = tool_name
        self.tool_args = tool_args
        super().__init__(f"Confirmation required for '{tool_name}'")


class ModelRouter:
    def __init__(self, settings: Settings):
        self.settings = settings
        self.ollama = OllamaProvider(settings)
        self.azure = AzureOpenAIProvider(settings) if settings.azure_configured else None
        self.memory = SQLiteMemory()
        skill_registry.autodiscover("Sergeant.skills")
        logger.info("ModelRouter initialized with %d skills", len(skill_registry.all()))

    async def generate(
        self,
        user_text: str,
        force_provider: str | None = None,
        chat_id: int | None = None,
    ) -> ModelResponse:
        
        history = self.memory.get_history(chat_id) if chat_id else []
        
        messages = [ModelMessage(role="system", content=SYSTEM_PROMPT)]
        messages.extend(history)
        
        new_msg = ModelMessage(role="user", content=user_text)
        messages.append(new_msg)

        if chat_id:
            self.memory.add_message(chat_id, new_msg)

        provider = force_provider or self.settings.model_primary
        
        if provider == "local" or provider == "ollama":
            response = await self._run_with_tools(self.ollama, messages, chat_id)
        elif provider == "azure":
            response = await self._generate_with_azure_fallback(messages, chat_id)
        else:
            logger.warning("Unknown provider %r, falling back to Ollama", provider)
            response = await self._run_with_tools(self.ollama, messages, chat_id)

        if chat_id and response.text:
            self.memory.add_message(chat_id, ModelMessage(role="assistant", content=response.text))

        return response

    async def resume_after_confirmation(
        self,
        chat_id: int,
        approved: bool,
    ) -> ModelResponse:
        pending = pending_store.get(chat_id)
        if pending is None:
            return ModelResponse(text="No pending actions to confirm.", provider="system", model="-")

        pending_store.clear(chat_id)
        provider_obj = self.azure if pending.provider_name == "azure" else self.ollama

        messages = list(pending.conversation)

        if not approved:
            messages.append(
                ModelMessage(
                    role="tool",
                    content=json.dumps({"ok": False, "error": "User cancelled the execution."}, ensure_ascii=False),
                    tool_call_id=pending.tool_call_id,
                    name=pending.tool_name,
                )
            )
        else:
            result = await self._execute_tool_call_unsafe(pending.tool_name, pending.tool_args)
            messages.append(
                ModelMessage(
                    role="tool",
                    content=json.dumps(result, ensure_ascii=False),
                    tool_call_id=pending.tool_call_id,
                    name=pending.tool_name,
                )
            )

        response = await self._run_with_tools(provider_obj, messages, chat_id)
        
        if chat_id and response.text:
            self.memory.add_message(chat_id, ModelMessage(role="assistant", content=response.text))
            
        return response

    async def _generate_with_azure_fallback(
        self,
        messages: list[ModelMessage],
        chat_id: int | None,
    ) -> ModelResponse:
        if self.azure is None:
            logger.warning("Azure not configured. Using Ollama.")
            return await self._run_with_tools(self.ollama, messages, chat_id)
        try:
            return await self._run_with_tools(self.azure, messages, chat_id)
        except (RateLimitError, APITimeoutError, APIError, httpx.HTTPError) as exc:
            logger.warning(
                "Azure failed due to a technical reason: %s. Using Ollama fallback.",
                repr(exc),
            )
            return await self._run_with_tools(self.ollama, messages, chat_id)
        except ConfirmationRequired:
            raise
        except Exception as exc:
            logger.exception(
                "Unexpected error in Azure: %s. Using Ollama fallback.",
                repr(exc),
            )
            return await self._run_with_tools(self.ollama, messages, chat_id)

    async def _run_with_tools(
        self,
        provider,
        messages: list[ModelMessage],
        chat_id: int | None,
    ) -> ModelResponse:
        tools = skill_registry.to_openai_tools()
        provider_name = "azure" if provider is self.azure else "ollama"

        for _ in range(MAX_TOOL_ITERATIONS):
            response = await provider.generate(messages, tools=tools if tools else None)

            if not response.tool_calls:
                return response

            messages.append(
                ModelMessage(
                    role="assistant",
                    content=response.text or None,
                    tool_calls=[
                        {
                            "id": tc.id,
                            "type": "function",
                            "function": {"name": tc.name, "arguments": tc.arguments},
                        }
                        for tc in response.tool_calls
                    ],
                )
            )
            
            if chat_id:
                self.memory.add_message(chat_id, messages[-1])

            for tool_call in response.tool_calls:
                definition = skill_registry.get(tool_call.name)

                if definition is not None and definition.requires_confirmation:
                    if chat_id is None:
                        logger.warning(
                            "Skill '%s' requires confirmation but no chat_id is available; rejecting.",
                            tool_call.name,
                        )
                        result = {"ok": False, "error": "This action requires user confirmation."}
                        messages.append(
                            ModelMessage(
                                role="tool",
                                content=json.dumps(result, ensure_ascii=False),
                                tool_call_id=tool_call.id,
                                name=tool_call.name,
                            )
                        )
                        continue

                    try:
                        args = json.loads(tool_call.arguments or "{}")
                    except json.JSONDecodeError:
                        args = {}

                    pending_store.set(
                        PendingConfirmation(
                            chat_id=chat_id,
                            tool_name=tool_call.name,
                            tool_args=args,
                            tool_call_id=tool_call.id,
                            provider_name=provider_name,
                            conversation=messages,
                        )
                    )
                    raise ConfirmationRequired(tool_call.name, args)

                result = await self._execute_tool_call(tool_call)
                tool_msg = ModelMessage(
                    role="tool",
                    content=json.dumps(result, ensure_ascii=False),
                    tool_call_id=tool_call.id,
                    name=tool_call.name,
                )
                messages.append(tool_msg)
                
                if chat_id:
                    self.memory.add_message(chat_id, tool_msg)

        logger.warning("Max tool iterations reached (%s)", MAX_TOOL_ITERATIONS)
        return ModelResponse(
            text="Task could not be completed after several tool iterations.",
            provider=response.provider,
            model=response.model,
        )

    async def _execute_tool_call(self, tool_call) -> dict:
        try:
            args = json.loads(tool_call.arguments or "{}")
        except json.JSONDecodeError:
            return {"error": "Invalid JSON arguments"}
        return await self._execute_tool_call_unsafe(tool_call.name, args)

    async def _execute_tool_call_unsafe(self, tool_name: str, args: dict) -> dict:
        definition = skill_registry.get(tool_name)
        if definition is None:
            logger.warning("Requested skill '%s' not registered", tool_name)
            return {"error": f"Skill '{tool_name}' not found"}

        logger.info("Executing skill '%s' with args=%s", tool_name, args)
        try:
            if skill_registry.is_async(definition.func):
                result = await definition.func(**args)
            else:
                result = definition.func(**args)
            return {"ok": True, "result": result}
        except Exception as exc:
            logger.exception("Error executing skill '%s'", tool_name)
            return {"ok": False, "error": str(exc)}